import CTA from "@/components/CTA/CTA";
import GetConnect from "@/components/GetConnect/GetConnect";
import Header from "@/components/Header/Header";
import HeroSection from "@/components/HeroSection/HeroSection";
import PopularProducts from "@/components/PopularProducts/PopularProducts";
import Head from "next/head";
import FeaturedSection from './../components/FeaturedSection/FeaturedSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>kacha bazar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HeroSection />
        <FeaturedSection />
        <PopularProducts />
        <CTA />
        <GetConnect />
      </main>
    </>
  );
}
